### ISSUE TITLE
MessageType fullName error

### ISSUE THREAD

**Issue by niluzhou1984** [square/protoparser#89]
file.proto
package example.simple;

message Message1 {
    optional string bestHuman = 1;
}
this proto file will generate example.simple.file.Message1
by google proto compiler

but square/protoparser will 
getFullyQualifiedName as example.simple.Message1

**Comment by JakeWharton** [comment]
What do you mean by "generate example.simple.file.Message1 by google proto compiler"? Do you mean that its internal model will use this format or do you mean that the code that gets generated (like Java) will use it.

**Comment by niluzhou1984** [comment]
the java code generated by protoc is  example.simple.file.Message1
but square/protoparser 's
getFullyQualifiedName return example.simple.Message1.

**Comment by JakeWharton** [comment]
ProtoParser is a representation of the schema. You could assemble `example.simple.file.Message1` from the component parts of the package name, file name, and message name. This project does not create any files though.

If you are referring to Wire that's a different project with different views. One specifically being that we ignore the file name and stick to traditional package + message naming concatenation.
