### ISSUE TITLE
Parse IDL while has default value will throw exception

### ISSUE THREAD

**Issue by Baidu-etech** [square/protoparser#91]
idl code as follow:
"package tutorial;" +
            "option java_package = \"com.example.tutorial\";" 
            "option java_outer_classname = \"AddressBookProtos\";" 
            " message PhoneNumber {" 
                "required int32 number = 1 [default = 1];" 
          "}"; 

while call field.getDefault(); will throw cast exception due to integer can not cast to String

    public String getDefault() {
      Option defaultOption = Option.findByName(options, "default");
      return defaultOption != null ? (String) defaultOption.getValue() : null;
    }

**Comment by Baidu-etech** [comment]
test version 3.1.5

**Comment by JakeWharton** [comment]
This has been fixed on `master` and we're hoping for a 4.0.0 release this month! Sorry about the trouble, I believe 3.1.4 should work if you want to downgrade to it temporarily.
